//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Strings
{
    using System;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI()
        {
        }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Asignar Tripulación.
        /// </summary>
        public static string AssignCrew
        {
            get
            {
                return ResourceManager.GetString("AssignCrew", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a A Tiempo.
        /// </summary>
        public static string ATiempo
        {
            get
            {
                return ResourceManager.GetString("ATiempo", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Retrasado.
        /// </summary>
        public static string Atrasado
        {
            get
            {
                return ResourceManager.GetString("Atrasado", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Autorizado.
        /// </summary>
        public static string Autorizado
        {
            get
            {
                return ResourceManager.GetString("Autorizado", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Confirmado.
        /// </summary>
        public static string Confirmado
        {
            get
            {
                return ResourceManager.GetString("Confirmado", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Finalizado.
        /// </summary>
        public static string Finalizado
        {
            get
            {
                return ResourceManager.GetString("Finalizado", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string Home
        {
            get
            {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Recursos Humanos.
        /// </summary>
        public static string HumanResources
        {
            get
            {
                return ResourceManager.GetString("HumanResources", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Incumpliendo.
        /// </summary>
        public static string Incumpliendo
        {
            get
            {
                return ResourceManager.GetString("Incumpliendo", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Listado de {0}.
        /// </summary>
        public static string Listing
        {
            get
            {
                return ResourceManager.GetString("Listing", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Maquinista.
        /// </summary>
        public static string Machinist
        {
            get
            {
                return ResourceManager.GetString("Machinist", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string New
        {
            get
            {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Operaciones.
        /// </summary>
        public static string Operations
        {
            get
            {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Programado.
        /// </summary>
        public static string Programado
        {
            get
            {
                return ResourceManager.GetString("Programado", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string Select
        {
            get
            {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Jefe de Tren.
        /// </summary>
        public static string TrainChief
        {
            get
            {
                return ResourceManager.GetString("TrainChief", resourceCulture);
            }
        }
    }
}
