//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfConvoy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ET_Convoy_Detalle
    {
        public int IdEtConvoyDetalle { get; set; }
        public int IdEtConvoyCabecera { get; set; }
        public string PesCarIde { get; set; }
        public string PesCarDes { get; set; }
        public Nullable<int> PesConId { get; set; }
        public string PesConDes { get; set; }
        public string PesConSelPor { get; set; }
    
        public virtual ET_Convoy_Cabecera ET_Convoy_Cabecera { get; set; }
    }
}
