//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfConvoy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ET_Convoy_Cabecera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ET_Convoy_Cabecera()
        {
            this.ET_Convoy_Detalle = new HashSet<ET_Convoy_Detalle>();
        }
    
        public int IdEtConvoyCabecera { get; set; }
        public Nullable<int> CnvBseCod { get; set; }
        public Nullable<int> CnvBasCod { get; set; }
        public string CnvID { get; set; }
        public string CnvObs { get; set; }
        public Nullable<int> CnvCicPesCod { get; set; }
        public Nullable<int> CnvChoid { get; set; }
        public string CnvChoDid { get; set; }
        public string CnvChoNom { get; set; }
        public Nullable<bool> Procesado { get; set; }
        public string IdCV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ET_Convoy_Detalle> ET_Convoy_Detalle { get; set; }
    }
}
