//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfConvoy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrazabilidadEntities : DbContext
    {
        public TrazabilidadEntities()
            : base("name=TrazabilidadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ET_Convoy_Cabecera> ET_Convoy_Cabecera { get; set; }
        public virtual DbSet<ET_Convoy_Detalle> ET_Convoy_Detalle { get; set; }
    }
}
