//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfRegistroPesaje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrazabilidadDBEntities : DbContext
    {
        public TrazabilidadDBEntities()
            : base("name=TrazabilidadDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ET_Pesaje_Cabecera> ET_Pesaje_Cabecera { get; set; }
        public virtual DbSet<ET_Pesaje_Detalle> ET_Pesaje_Detalle { get; set; }
        public virtual DbSet<ET_Pesaje_Sello> ET_Pesaje_Sello { get; set; }
    }
}
