//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Strings
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AzureGroups
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AzureGroups()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings.AzureGroups", typeof(AzureGroups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 425e8c08-b3d7-4367-af6e-8dc9780c5e9f.
        /// </summary>
        public static string PlatformAdmin
        {
            get
            {
                return ResourceManager.GetString("PlatformAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0f15f548-706b-434d-8759-00dae6d589b1.
        /// </summary>
        public static string PlatformCrew
        {
            get
            {
                return ResourceManager.GetString("PlatformCrew", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to aa0726a3-3bfc-4788-af4b-73c4dad3dcdc.
        /// </summary>
        public static string PlatformHumanResources
        {
            get
            {
                return ResourceManager.GetString("PlatformHumanResources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 3c7bd12d-41e7-4d8f-bfaa-ab592bd4030d.
        /// </summary>
        public static string PlatformManager
        {
            get
            {
                return ResourceManager.GetString("PlatformManager", resourceCulture);
            }
        }
    }
}
