//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Models {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings.Models", typeof(Models).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carro.
        /// </summary>
        public static string Carro {
            get {
                return ResourceManager.GetString("Carro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conductor.
        /// </summary>
        public static string Conductor {
            get {
                return ResourceManager.GetString("Conductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenedor.
        /// </summary>
        public static string Contenedor {
            get {
                return ResourceManager.GetString("Contenedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Locomotora.
        /// </summary>
        public static string Locomotora {
            get {
                return ResourceManager.GetString("Locomotora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta.
        /// </summary>
        public static string Ruta {
            get {
                return ResourceManager.GetString("Ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statu.
        /// </summary>
        public static string Statu {
            get {
                return ResourceManager.GetString("Statu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trazabilidad.
        /// </summary>
        public static string Trazabilidad {
            get {
                return ResourceManager.GetString("Trazabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TrazabilidadMovCarro.
        /// </summary>
        public static string TrazabilidadMovCarro {
            get {
                return ResourceManager.GetString("TrazabilidadMovCarro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TrazabilidadMovLocomotora.
        /// </summary>
        public static string TrazabilidadMovLocomotora {
            get {
                return ResourceManager.GetString("TrazabilidadMovLocomotora", resourceCulture);
            }
        }
    }
}
