//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfArmado
{
    using System;
    using System.Collections.Generic;
    
    public partial class IG_Log_Armado
    {
        public int IdIGLog { get; set; }
        public string Texto { get; set; }
        public string Estado { get; set; }
        public string Descripcion_Estado { get; set; }
    }
}
