//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfArmado
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrazabilidadArmadoDBEntities : DbContext
    {
        public TrazabilidadArmadoDBEntities()
            : base("name=TrazabilidadArmadoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IG_Armado> IG_Armado { get; set; }
        public virtual DbSet<IG_Mov_Armado> IG_Mov_Armado { get; set; }
    }
}
