//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WcfConvoy.ws_Convoy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSEtruckTrenesSoapBinding", Namespace="SaladilloEtruckTrenes")]
    public partial class WSEtruckTrenes : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WS_REGISTRO_CONVOYOperationCompleted;
        
        private System.Threading.SendOrPostCallback WS_REGISTRO_SELLOOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSEtruckTrenes() {
            this.Url = global::WcfConvoy.Properties.Settings.Default.WcfConvoy_ws_Convoy_WSEtruckTrenes;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WS_REGISTRO_CONVOYCompletedEventHandler WS_REGISTRO_CONVOYCompleted;
        
        /// <remarks/>
        public event WS_REGISTRO_SELLOCompletedEventHandler WS_REGISTRO_SELLOCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SaladilloEtruckTrenesaction/AWSETRUCKTRENES.WS_REGISTRO_CONVOY", RequestElementName="WSEtruckTrenes.WS_REGISTRO_CONVOY", RequestNamespace="SaladilloEtruckTrenes", ResponseElementName="WSEtruckTrenes.WS_REGISTRO_CONVOYResponse", ResponseNamespace="SaladilloEtruckTrenes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Sdt_respuesta")]
        public Respuesta WS_REGISTRO_CONVOY(Registro_Convoy Sdt_registro_convoy) {
            object[] results = this.Invoke("WS_REGISTRO_CONVOY", new object[] {
                        Sdt_registro_convoy});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void WS_REGISTRO_CONVOYAsync(Registro_Convoy Sdt_registro_convoy) {
            this.WS_REGISTRO_CONVOYAsync(Sdt_registro_convoy, null);
        }
        
        /// <remarks/>
        public void WS_REGISTRO_CONVOYAsync(Registro_Convoy Sdt_registro_convoy, object userState) {
            if ((this.WS_REGISTRO_CONVOYOperationCompleted == null)) {
                this.WS_REGISTRO_CONVOYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWS_REGISTRO_CONVOYOperationCompleted);
            }
            this.InvokeAsync("WS_REGISTRO_CONVOY", new object[] {
                        Sdt_registro_convoy}, this.WS_REGISTRO_CONVOYOperationCompleted, userState);
        }
        
        private void OnWS_REGISTRO_CONVOYOperationCompleted(object arg) {
            if ((this.WS_REGISTRO_CONVOYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WS_REGISTRO_CONVOYCompleted(this, new WS_REGISTRO_CONVOYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SaladilloEtruckTrenesaction/AWSETRUCKTRENES.WS_REGISTRO_SELLO", RequestElementName="WSEtruckTrenes.WS_REGISTRO_SELLO", RequestNamespace="SaladilloEtruckTrenes", ResponseElementName="WSEtruckTrenes.WS_REGISTRO_SELLOResponse", ResponseNamespace="SaladilloEtruckTrenes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Sdt_respuesta")]
        public Respuesta WS_REGISTRO_SELLO([System.Xml.Serialization.XmlArrayItemAttribute(Namespace="SaladilloEtruckCamiones", IsNullable=false)] SDT_Registro_SelloSDT_Registro_SelloItem[] Sdt_registro_sello) {
            object[] results = this.Invoke("WS_REGISTRO_SELLO", new object[] {
                        Sdt_registro_sello});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void WS_REGISTRO_SELLOAsync(SDT_Registro_SelloSDT_Registro_SelloItem[] Sdt_registro_sello) {
            this.WS_REGISTRO_SELLOAsync(Sdt_registro_sello, null);
        }
        
        /// <remarks/>
        public void WS_REGISTRO_SELLOAsync(SDT_Registro_SelloSDT_Registro_SelloItem[] Sdt_registro_sello, object userState) {
            if ((this.WS_REGISTRO_SELLOOperationCompleted == null)) {
                this.WS_REGISTRO_SELLOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWS_REGISTRO_SELLOOperationCompleted);
            }
            this.InvokeAsync("WS_REGISTRO_SELLO", new object[] {
                        Sdt_registro_sello}, this.WS_REGISTRO_SELLOOperationCompleted, userState);
        }
        
        private void OnWS_REGISTRO_SELLOOperationCompleted(object arg) {
            if ((this.WS_REGISTRO_SELLOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WS_REGISTRO_SELLOCompleted(this, new WS_REGISTRO_SELLOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SaladilloEtruckCamiones")]
    public partial class Registro_Convoy {
        
        private short cnvBseCodField;
        
        private short cnvBasCodField;
        
        private long cnvIDField;
        
        private string cnvObsField;
        
        private short cnvCicPesCodField;
        
        private long cnvChoIDField;
        
        private string cnvChoDVField;
        
        private string cnvChoNomField;
        
        private SDT_Registro_ConvoyPesCarItem[] pesCarField;
        
        /// <remarks/>
        public short CnvBseCod {
            get {
                return this.cnvBseCodField;
            }
            set {
                this.cnvBseCodField = value;
            }
        }
        
        /// <remarks/>
        public short CnvBasCod {
            get {
                return this.cnvBasCodField;
            }
            set {
                this.cnvBasCodField = value;
            }
        }
        
        /// <remarks/>
        public long CnvID {
            get {
                return this.cnvIDField;
            }
            set {
                this.cnvIDField = value;
            }
        }
        
        /// <remarks/>
        public string CnvObs {
            get {
                return this.cnvObsField;
            }
            set {
                this.cnvObsField = value;
            }
        }
        
        /// <remarks/>
        public short CnvCicPesCod {
            get {
                return this.cnvCicPesCodField;
            }
            set {
                this.cnvCicPesCodField = value;
            }
        }
        
        /// <remarks/>
        public long CnvChoID {
            get {
                return this.cnvChoIDField;
            }
            set {
                this.cnvChoIDField = value;
            }
        }
        
        /// <remarks/>
        public string CnvChoDV {
            get {
                return this.cnvChoDVField;
            }
            set {
                this.cnvChoDVField = value;
            }
        }
        
        /// <remarks/>
        public string CnvChoNom {
            get {
                return this.cnvChoNomField;
            }
            set {
                this.cnvChoNomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PesCarItem", IsNullable=false)]
        public SDT_Registro_ConvoyPesCarItem[] PesCar {
            get {
                return this.pesCarField;
            }
            set {
                this.pesCarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SDT_Registro_Convoy.PesCarItem", Namespace="SaladilloEtruckCamiones")]
    public partial class SDT_Registro_ConvoyPesCarItem {
        
        private string pesCarIdeField;
        
        private string pesCarDesField;
        
        private long pesConIdField;
        
        private string pesConDesField;
        
        /// <remarks/>
        public string PesCarIde {
            get {
                return this.pesCarIdeField;
            }
            set {
                this.pesCarIdeField = value;
            }
        }
        
        /// <remarks/>
        public string PesCarDes {
            get {
                return this.pesCarDesField;
            }
            set {
                this.pesCarDesField = value;
            }
        }
        
        /// <remarks/>
        public long PesConId {
            get {
                return this.pesConIdField;
            }
            set {
                this.pesConIdField = value;
            }
        }
        
        /// <remarks/>
        public string PesConDes {
            get {
                return this.pesConDesField;
            }
            set {
                this.pesConDesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SDT_Registro_Sello.SDT_Registro_SelloItem", Namespace="SaladilloEtruckCamiones")]
    public partial class SDT_Registro_SelloSDT_Registro_SelloItem {
        
        private string pesCarIdeField;
        
        private long pesConIdField;
        
        private string pesConSelPorField;
        
        /// <remarks/>
        public string PesCarIde {
            get {
                return this.pesCarIdeField;
            }
            set {
                this.pesCarIdeField = value;
            }
        }
        
        /// <remarks/>
        public long PesConId {
            get {
                return this.pesConIdField;
            }
            set {
                this.pesConIdField = value;
            }
        }
        
        /// <remarks/>
        public string PesConSelPor {
            get {
                return this.pesConSelPorField;
            }
            set {
                this.pesConSelPorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SDT_Respuesta.SDTWSRespuestaItem", Namespace="SaladilloEtruckTrenes")]
    public partial class SDT_RespuestaSDTWSRespuestaItem {
        
        private string sDTWSRespuestaIdField;
        
        private string sDTWSRespuestaDescripcionField;
        
        /// <remarks/>
        public string SDTWSRespuestaId {
            get {
                return this.sDTWSRespuestaIdField;
            }
            set {
                this.sDTWSRespuestaIdField = value;
            }
        }
        
        /// <remarks/>
        public string SDTWSRespuestaDescripcion {
            get {
                return this.sDTWSRespuestaDescripcionField;
            }
            set {
                this.sDTWSRespuestaDescripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SaladilloEtruckTrenes")]
    public partial class Respuesta {
        
        private System.Nullable<System.DateTime> sDTWSRespuestaFechaField;
        
        private System.Nullable<System.DateTime> sDTWSRespuestaHoraField;
        
        private SDT_RespuestaSDTWSRespuestaItem[] sDTWSRespuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> SDTWSRespuestaFecha {
            get {
                return this.sDTWSRespuestaFechaField;
            }
            set {
                this.sDTWSRespuestaFechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SDTWSRespuestaHora {
            get {
                return this.sDTWSRespuestaHoraField;
            }
            set {
                this.sDTWSRespuestaHoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SDTWSRespuestaItem", IsNullable=false)]
        public SDT_RespuestaSDTWSRespuestaItem[] SDTWSRespuesta {
            get {
                return this.sDTWSRespuestaField;
            }
            set {
                this.sDTWSRespuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WS_REGISTRO_CONVOYCompletedEventHandler(object sender, WS_REGISTRO_CONVOYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WS_REGISTRO_CONVOYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WS_REGISTRO_CONVOYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WS_REGISTRO_SELLOCompletedEventHandler(object sender, WS_REGISTRO_SELLOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WS_REGISTRO_SELLOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WS_REGISTRO_SELLOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591